### PR TITLE
work on updating python and django versions compatibility

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by auvipy** [comment]
should I remove the unsupported versions?

**Comment by tomchristie** [comment]
Looking good :+1:

Also required: `README.md` and `docs/index.md`

> should I remove the unsupported versions?

Which unsupported versions?

**Comment by carltongibson** [comment]
> Which unsupported versions?

I presume @auvipy means unsupported Django versions. I'd say "Yes, remove them".

On the test failures: 

* Remove the `--use-mirrors` flag to `pip`. https://github.com/tomchristie/django-vanilla-views/blob/master/.travis.yml#L19
* Python 3.2 will need `coverage==3.7.1` (IIRC) since 4.x drops support.

**Comment by auvipy** [comment]
Ok guys

**Comment by tomchristie** [comment]
Note some test cases still failing.

**Comment by auvipy** [comment]
https://github.com/tomchristie/django-vanilla-views/pull/50 new PR

**Pull request closed without merging**
