### PR TITLE
Test with Django 2.0 and 2.1, and other updates

### PR DESCRIPTION
**Pull request by adamchainz**
* Make example project work without any of its own warnings on Django 1.8+, shrink settings file to minimum required, update README on running it
* tox test with all django/python versions
* Update to avoid throwing warnings on any version of django
* Update Travis grid
* Update documentation in README and setup.py about supported versions

Test Plan:

* Ran example project locally on Python 3.7 with each Django version from 1.8 upwards, fixed warnings.
* Ran tox locally, for the Python versions I have installed it passes.
* Watching Travis pass.

### CODE REVIEW

**Comment by adamchainz** [comment]
Supercedes #69

**Comment by adamchainz** [comment]
Fixes #71

**Comment by adamchainz** [comment]
@tomchristie @carltongibson could this get some attention? Maybe even make me a maintainer? 😇🙌

**Comment by tomchristie** [comment]
@adamchainz Sounds like a good plan yup! Will sort that as soon as am at a keyboard. Can you give me a pypi username?

**Comment by adamchainz** [comment]
```
My PyPI username is adamchainz
-----BEGIN PGP MESSAGE-----

owEBbAKT/ZANAwAIAexxJck0iDvlAcslYgBb6ugdTXkgUHlQSSB1c2VybmFtZSBp
cyBhZGFtY2hhaW56CokCMwQAAQgAHRYhBJExaSSkbFcLB32M0exxJck0iDvlBQJb
6ugjAAoJEOxxJck0iDvlHK0QALNEUv2leVwtiIYNx4wQWZlFatKXeT8NXg8H24OM
4tNPbQYqQH1ZABxqQg1cycUM+Y9tUediR8dcVlVvJpJbHoRdHJURPb+Cy0YtH5IK
ojwPsM9SxidHlwx/GHmqXnvyXrqdmCXo6CY9Pv7/9e4apfW0w95WW/mWJey0Ue4z
PsNwSzd/s2+LCFqovco6Pxrmg8B6CxGj7J3LP+iywSwIjP2N/D5UDepjho6gM/+H
uDsv6r3bGY9iR+ndLS/WqouG0iVB77aFoaCfzhV/0qAk9K0QgDi6pRg6YOtxxmWF
d0fZMo6Fi+zHeJI3OiYDKJ62znDTcBgjgVsyaV7/VywPZKL7h907Jf2Kobm47yKg
OOq0ZiJurZZOXmo56Ob0+vgXQ22y89m3zss98t2Hmww5cV5lFD30eemrCFfN3gYX
HQVKOci4mlmirX06loV2ie1eEry4goqURP8oe+ImNhwoHeCJW+uq3hEvGLmqk/kB
ArARPq9xzPfC0jS6EJ7Mct7A8BFEuY8Aiv79JiFNjbY0FSm+RDBkzKMApI0JgBLI
pXwjhQCwqNl4o+Srv4Q4mhmOKo8IGE10FXlLggPhywg1+2d11+16+sNIedu9Fukt
d34w0GRcuWSG8Th2HhNdbqIC9cB/bApKJZA2AOP4Xi34N+hNpgd8Zj/zfs8PWsf4
yJ5D
=eTFB
-----END PGP MESSAGE-----
```
https://keybase.io/adamchainz
https://xkcd.com/1181/ xD

**Comment by tomchristie** [comment]
@adamchainz Okey doke. Invited you as a collaborator here, and added you as a maintainer on PyPI.
Let me know if you bump into any issues trying to roll a new release & docs.

**Comment by tomchristie** [comment]
@adamchainz Also very much considering moving to @encode, on promoting from @carltongibson.

**Comment by adamchainz** [comment]
😎 I'm in , will look at merging and releasing, thanks

**Pull request merged**
