### PR TITLE
new versions on test matrix

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by tomchristie** [comment]
Good plan with the upgrades here.
Coupla failures on the test run that need looking into.

**Comment by auvipy** [comment]
I will look into them

**Comment by audiolion** [comment]
looks like the 1.11 tests needs the updated path for core/urlresolvers, probably use a `compat` file to conditionally import it?

**Comment by auvipy** [comment]
ok

**Comment by ssteinerx** [comment]
Support for 1.9 ended on August 1st, 2017 so it'd probably be good to also remove it from the test matrix and supported releases.

**Comment by auvipy** [comment]
awh! I totally forgot about this PR

**Pull request closed without merging**
